### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by MichaelV25** [RouHim/disCoverJ#70]
Nach der Installtion von discoverJ kann ich das Programm direkt starten. Wenn ich es aber beendet und erneut starten möchte, dann erhalte ich immer folgende Fehlermeldung:

`java.lang.UnsupportedClassVersionError: de/itlobby/discoverj/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:512)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:420)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:414)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:413)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
`

**Comment by RouHim** [comment]
Hallo, danke für die Fehlermeldung.
Schaue ich mir direkt mal an!

**Comment by RouHim** [comment]
@MichaelV25 Ich habe ein Update veröffentlich, bitte nochmal versuchen.

**Comment by MichaelV25** [comment]
Danke für die schnelle Prüfung. Die Version "412.1.9_257A" habe ich soeben installiert. Das Verhalten bleibt gleich: Nach der Installation lässt es sich direkt öffnen. Nach dem Schließen und erneuten Öffnen erhalte ich die gleiche Fehlermeldung:
`java.lang.UnsupportedClassVersionError: de/itlobby/discoverj/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:512)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:420)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:414)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:413)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
`

**Comment by RouHim** [comment]
Alles klar danke für das Update. 

Auf welchem Betriebssystem läuft das Programm?

Mal versucht zu deinstallieren und es bei zu installieren?

**Comment by MichaelV25** [comment]
Windows 10 Pro 22H2

Habe soeben discoverJ deinstalliert, System neu gestartet und neu installiert. Das Verhalten bleibt das gleiche.

Nach der Fehlermeldung habe ich einmal gegoogelt. Kann es sein, dass ein OpenJDK 17 benötigt wird, während ein OpenJDK 16 ausgeliefert wird? Mir erschließt sich zwar nicht, warum discoverJ nach der Installation aussgeführt wird und nach einem erneuten Öffnen nicht mehr; aber vielleicht liegt es darin begründet?

**Comment by RouHim** [comment]
Also es wird ein JDK 17 vorausgesetzt, dieses wird jedoch automatisch installiert falls nicht gefunden. Deshalb wundert es mich warum er beim zweiten Start ein altes JDK verendet.

**Comment by MichaelV25** [comment]
Fehler gefunden und gelöst.

Es war noch unter C:\Programme eine ältere Version von discoverJ installiert, in der ich auch das JDK 16  gesehen hatte. Ich hatte nach der Deinstallation nicht darauf geachtet, dass das Verzeichnis komplett weggeräumt wird und mich gerade nach der erneut durchgeführten Deinstallation gewundert, dass einige Dateien und das JRE-Verzeichnis bestehen blieben. Dann habe ich festgestellt, dass die Bereitstellung mittlerweile über \Users\...\.jdeploy\apps\discoverj erfolgt.

Danke für die schnelle Unterstützung. Sorry wegen der Tomaten auf den Augen.

**Comment by RouHim** [comment]
Kein Problem, super das du das Problem selber lösen konntest :)
